CREATE SEQUENCE IF NOT EXISTS user_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE categories_medicines
(
    category_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(255),
    CONSTRAINT pk_categories_medicines PRIMARY KEY (category_id)
);

CREATE TABLE clients
(
    client_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    email         VARCHAR(255),
    phone         VARCHAR(255),
    address       VARCHAR(255),
    profile_photo VARCHAR(255),
    birth_date    TIMESTAMP WITHOUT TIME ZONE,
    gender        VARCHAR(255),
    dni           VARCHAR(8)                              NOT NULL,
    status        VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (client_id)
);

CREATE TABLE employees
(
    employee_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    email         VARCHAR(255),
    phone         VARCHAR(255),
    address       VARCHAR(255),
    profile_photo VARCHAR(255),
    birth_date    TIMESTAMP WITHOUT TIME ZONE,
    gender        VARCHAR(255),
    type_employee VARCHAR(255)                            NOT NULL,
    legend_color  VARCHAR(255),
    CONSTRAINT pk_employees PRIMARY KEY (employee_id)
);

CREATE TABLE invoices
(
    invoice_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at     TIMESTAMP WITHOUT TIME ZONE,
    number               VARCHAR(255),
    total_amount         DOUBLE PRECISION,
    client_id            BIGINT,
    pet_id               BIGINT,
    medical_procedure_id BIGINT,
    CONSTRAINT pk_invoices PRIMARY KEY (invoice_id)
);

CREATE TABLE medicine_stocks
(
    stock_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    quantity         BIGINT                                  NOT NULL,
    expiration_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_medicine_stocks PRIMARY KEY (stock_id)
);

CREATE TABLE medicines
(
    medicine_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at   TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255)                            NOT NULL,
    laboratory         VARCHAR(255),
    label_volume       VARCHAR(255),
    quantity_per_stock BIGINT,
    manufacturer       VARCHAR(255),
    supplier           VARCHAR(255),
    label_whole        VARCHAR(255),
    label_stock        VARCHAR(255),
    price              DOUBLE PRECISION,
    category_id        BIGINT,
    stock_id           BIGINT,
    CONSTRAINT pk_medicines PRIMARY KEY (medicine_id)
);

CREATE TABLE pets
(
    pet_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(45)                             NOT NULL,
    breed            VARCHAR(45)                             NOT NULL,
    color            VARCHAR(45)                             NOT NULL,
    species          VARCHAR(45)                             NOT NULL,
    birth_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    gender           VARCHAR(255),
    microchip_id     VARCHAR(45),
    weight           DOUBLE PRECISION,
    next_visit       TIMESTAMP WITHOUT TIME ZONE,
    photo_url        VARCHAR(255),
    client_id        BIGINT,
    CONSTRAINT pk_pets PRIMARY KEY (pet_id)
);

CREATE TABLE procedures
(
    procedure_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    medical_procedure VARCHAR(255),
    remarks           TEXT,
    next_due_date     TIMESTAMP WITHOUT TIME ZONE,
    status            VARCHAR(255),
    weight            DOUBLE PRECISION,
    pet_id            BIGINT,
    employee_id       BIGINT,
    CONSTRAINT pk_procedures PRIMARY KEY (procedure_id)
);

CREATE TABLE roles
(
    role_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(45)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE schedules
(
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(45)                             NOT NULL,
    time_start  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    time_end    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    employee_id BIGINT,
    CONSTRAINT pk_schedules PRIMARY KEY (schedule_id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    username         VARCHAR(45)                             NOT NULL,
    password         VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE clients
    ADD CONSTRAINT uc_clients_dni UNIQUE (dni);

ALTER TABLE clients
    ADD CONSTRAINT uc_clients_email UNIQUE (email);

ALTER TABLE clients
    ADD CONSTRAINT uc_clients_phone UNIQUE (phone);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_phone UNIQUE (phone);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (client_id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_MEDICAL_PROCEDURE FOREIGN KEY (medical_procedure_id) REFERENCES procedures (procedure_id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (pet_id);

ALTER TABLE medicines
    ADD CONSTRAINT FK_MEDICINES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories_medicines (category_id);

ALTER TABLE medicines
    ADD CONSTRAINT FK_MEDICINES_ON_STOCK FOREIGN KEY (stock_id) REFERENCES medicine_stocks (stock_id);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (client_id);

ALTER TABLE procedures
    ADD CONSTRAINT FK_PROCEDURES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (employee_id);

ALTER TABLE procedures
    ADD CONSTRAINT FK_PROCEDURES_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (pet_id);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (employee_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);